fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    powershell: git://github.com/puppetlabs/puppetlabs-powershell.git
    selinux: git://github.com/jfryman/puppet-selinux.git
    rsyslog: git://github.com/ghoneycutt/puppet-module-rsyslog.git
  symlinks:
    al_agents: "#{source_dir}"