sudo: required
language: ruby
bundler_args: "--without system_tests"
script:
- bundle exec rake spec
rvm:
- 2.2.2
gemfile:
- Gemfile
branches:
  only:
  - master
env:
- PUPPET_GEM_VERSION="~> 4.0"
- PUPPET_GEM_VERSION="~> 3.0"
